module SampleGems
  NAMES = %w(
    rspec-core
    rspec-expectations
    rspec-mocks
    diff-lcs
    rspec-support
    rspec
    bundler
    multi_json
    rack
    rake
    rubygems-update
    i18n
    activesupport
    json
    mime-types
    tzinfo
    thor
    nokogiri
    builder
    minitest
    thread_safe
    tilt
    activemodel
    aws-sdk-core
    activerecord
    ffi
    actionpack
    addressable
    rails
    rack-test
    aws-sdk
    faraday
    mail
    actionmailer
    arel
    railties
    sass
    multipart-post
    concurrent-ruby
    sprockets
    erubis
    aws-sdk-resources
    mini_portile2
    method_source
    actionview
    jmespath
    execjs
    sprockets-rails
    uglifier
    public_suffix
    activejob
    mime-types-data
    loofah
    coderay
    rails-dom-testing
    rails-html-sanitizer
    rubyzip
    coffee-script-source
    aws-sigv4
    rest-client
    pry
    sass-rails
    globalid
    jquery-rails
    redis
    coffee-script
    daemons
    rack-protection
    net-ssh
    unf_ext
    domain_name
    netrc
    coffee-rails
    excon
    unf
    rb-fsevent
    rb-inotify
    sinatra
    http-cookie
    multi_xml
    jwt
    hashie
    eventmachine
    rubygems-bundler
    unicode-display_width
    pg
    ruby-progressbar
    byebug
    jbuilder
    httpclient
    slop
    rainbow
    childprocess
    websocket-driver
    parser
    faraday_middleware
    simplecov
    httparty
    awesome_print
    websocket-extensions
  )
end
