#!/usr/bin/env ruby

case ENV['RACK_ENV']
when 'development'
when 'production'
else
  puts "You should set value 'development'(to use SQLite3) or 'production'(to use PostgreSQL) to RACK_ENV environment variable."
  exit 1
end

require_relative '../lib/database'
require 'csv'

csv_base = ARGV[0]
unless csv_base
  puts "Usage  : import_db <path_to_csv_files>"
  puts "Example: import_db path/to/bsetgems_db_v5_sample_csv"
  exit 1
end

# Import definitions.
# [0] = CSV path, [1] = Model class 
defs = [
  ['/gems.csv', Gems],
  ['/values.csv', Value],
  ['/rankings.csv', Ranking],
  ['/reports.csv', Reports],
  ['/report_data.csv', ReportData],
  ['/statistics.csv', Statistics],
  ['/master.csv', Master],
]

CHUNK_SIZE = 5000

defs.each{|path, model|
  csv_path = csv_base + path
  CSV.open(csv_path).each_slice(CHUNK_SIZE).each_with_index{|rows, i|
    puts "Importing #{csv_path} to #{model} (#{i})"
    model.import(model.columns, rows)
  }
}

puts 'Completed!'
